#!/bin/sh

module="hello"
device="scull"
mode="664"

if grep -q '^staff:' /etc/group; then
	group="staff"
else
	group="wheel"
fi

/sbin/insmod ./$module.ko $* ||exit 1

major=$(awk "\$2 == \"$device\" {print \$1}" /proc/devices)
echo "major='$major'"
echo "group='$group'"
rm -f /dev/${device}
mknod /dev/${device} c $major 0 || exit 2
sudo chgrp $group /dev/${device}
sudo chmod $mode /dev/${device}
